#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
#ifndef TRANSITSDK_SWIFT_H
#define TRANSITSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import Security;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TransitSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// App环境检测工具
SWIFT_CLASS("_TtC10TransitSDK19AppEnvironmentUtils")
@interface AppEnvironmentUtils : NSObject
/// 是否在主线程
+ (BOOL)isMainThread SWIFT_WARN_UNUSED_RESULT;
/// 是否在调试模式
+ (BOOL)isBeingDebugged SWIFT_WARN_UNUSED_RESULT;
/// 是否越狱
+ (BOOL)isJailbroken SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)evidenceOfSymbolLinking SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)sandboxBreached SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)jailbreakFileExists SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)systemForkCall SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class UIWindow;

/// App工具
SWIFT_CLASS("_TtC10TransitSDK8AppUtils")
@interface AppUtils : NSObject
/// 获取 App BundleId
+ (NSString * _Nonnull)getAppBundleId SWIFT_WARN_UNUSED_RESULT;
/// 获取 App 版本
+ (NSString * _Nonnull)getAppVersion SWIFT_WARN_UNUSED_RESULT;
/// 获取 App Build号
+ (NSString * _Nonnull)getAppBuildNumber SWIFT_WARN_UNUSED_RESULT;
+ (UIWindow * _Nullable)getKeyWindow SWIFT_WARN_UNUSED_RESULT;
/// 打开url
+ (void)openUrlWithDomain:(NSString * _Nonnull)domain paramString:(NSString * _Nonnull)paramString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class NSData;

/// 字节数组转换工具
SWIFT_CLASS("_TtC10TransitSDK10BytesUtils")
@interface BytesUtils : NSObject
+ (NSArray<NSNumber *> * _Nonnull)toBytesWithString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSNumber *> * _Nonnull)toBytesWithData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSNumber *> * _Nonnull)toHexBytesWithString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSNumber *> * _Nonnull)toHexBytesWithData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK25CertificateSigningRequest")
@interface CertificateSigningRequest : NSObject
- (nonnull instancetype)init;
@end


/// 数据转换工具
SWIFT_CLASS("_TtC10TransitSDK9DataUtils")
@interface DataUtils : NSObject
+ (NSData * _Nonnull)toDataWithString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)toHexDataWithString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nullable)toBase64DecodedDataWithString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;

/// 日期转换工具
SWIFT_CLASS("_TtC10TransitSDK9DateUtils")
@interface DateUtils : NSObject
/// 转换日期
+ (NSDate * _Nullable)toDateFrom:(NSString * _Nonnull)dateString dateFormat:(NSString * _Nonnull)dateFormat SWIFT_WARN_UNUSED_RESULT;
/// 转换时间
+ (NSString * _Nonnull)toStringFrom:(NSDate * _Nonnull)date dateFormat:(NSString * _Nonnull)dateFormat SWIFT_WARN_UNUSED_RESULT;
/// 转换UTC时间
+ (NSString * _Nonnull)toUTCStringFrom:(NSDate * _Nonnull)date dateFormat:(NSString * _Nonnull)dateFormat SWIFT_WARN_UNUSED_RESULT;
/// 转时间戳
+ (NSInteger)toTimeStampFrom:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT;
/// 延后多少天
+ (NSDate * _Nonnull)delayFrom:(NSDate * _Nonnull)date days:(NSInteger)days SWIFT_WARN_UNUSED_RESULT;
/// 延后多少秒
+ (NSDate * _Nonnull)delayFrom:(NSDate * _Nonnull)date timeInterval:(NSInteger)timeInterval SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isExpiredWithExpiredTime:(NSString * _Nullable)expiredTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 设备工具
SWIFT_CLASS("_TtC10TransitSDK11DeviceUtils")
@interface DeviceUtils : NSObject
/// 是否是模拟器
+ (BOOL)isSimulator SWIFT_WARN_UNUSED_RESULT;
/// 获取设备标识
+ (NSString * _Nonnull)getModelIdentifier SWIFT_WARN_UNUSED_RESULT;
/// 获取系统名字
+ (NSString * _Nonnull)getSystemName SWIFT_WARN_UNUSED_RESULT;
/// 获取系统版本
+ (NSString * _Nonnull)getSystemVersion SWIFT_WARN_UNUSED_RESULT;
/// 生成一个UUID串
+ (NSString * _Nonnull)generateUUIDStringWithShouldFormat:(BOOL)shouldFormat SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






/// 钥匙串管理
SWIFT_CLASS("_TtC10TransitSDK15KeyChainManager")
@interface KeyChainManager : NSObject
/// 存证书到钥匙串
+ (BOOL)saveCertificateWithCertificate:(SecCertificateRef _Nonnull)certificate label:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
/// 从钥匙串获取证书
+ (SecCertificateRef _Nullable)getCertificateWithLabel:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
/// 删除证书
+ (BOOL)deleteCertificateWithLabel:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
/// 存秘钥到钥匙串
+ (BOOL)saveSecKeyWithKey:(SecKeyRef _Nonnull)key label:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
/// 从钥匙串获取秘钥
+ (SecKeyRef _Nullable)getKeyWithLabel:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
/// 删除秘钥
+ (BOOL)deleteKeyWithLabel:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
/// 存数据到钥匙串
+ (BOOL)saveDataWithData:(NSData * _Nonnull)data service:(NSString * _Nonnull)service account:(NSString * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
/// 从钥匙串获取数据
+ (NSData * _Nullable)getDataWithService:(NSString * _Nonnull)service account:(NSString * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
/// 删除数据
+ (BOOL)deleteDataWithService:(NSString * _Nonnull)service account:(NSString * _Nonnull)account SWIFT_WARN_UNUSED_RESULT;
/// 存秘钥过期时间到钥匙串
+ (BOOL)saveExpiredTimeWithExpiredTime:(NSString * _Nonnull)expiredTime label:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
/// 从钥匙串获取证书过期时间
+ (NSString * _Nullable)getExpiredTimeWithLabel:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
/// 删除过期时间
+ (BOOL)deleteExpiredTimeWithLabel:(NSString * _Nonnull)label SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





















/// 证书管理
SWIFT_CLASS("_TtC10TransitSDK21SecCertificateManager")
@interface SecCertificateManager : NSObject
/// 获取证书(从pem串)
+ (SecCertificateRef _Nullable)getCertificateFromPem:(NSString * _Nonnull)pem SWIFT_WARN_UNUSED_RESULT;
/// 获取Data
+ (NSData * _Nonnull)getDataFromCertificate:(SecCertificateRef _Nonnull)certificate SWIFT_WARN_UNUSED_RESULT;
/// 读取本地CA证书
+ (SecCertificateRef _Nullable)loadCACertificateWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
/// 通过CA(受信任证书)验证OB证书, 并获取OB证书的公钥
+ (SecKeyRef _Nullable)verifyOBCertificateWithCAWithObPemString:(NSString * _Nonnull)obPemString caPemString:(NSString * _Nonnull)caPemString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SecKeyPair;

/// 秘钥管理(生成配对秘钥, 获取公钥等)
SWIFT_CLASS("_TtC10TransitSDK13SecKeyManager")
@interface SecKeyManager : NSObject
/// 生成配对秘钥
+ (SecKeyPair * _Nullable)generateSecKeyPairWithDeviceId:(NSString * _Nonnull)deviceId SWIFT_WARN_UNUSED_RESULT;
/// 获取公钥
+ (SecKeyRef _Nullable)getPublicKeyWithCertificate:(SecCertificateRef _Nonnull)certificate SWIFT_WARN_UNUSED_RESULT;
/// 获取Data
+ (NSData * _Nullable)getDataFromSecKey:(SecKeyRef _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
/// 公钥加密数据(pkcs1)
+ (NSData * _Nullable)encryptWithPublicKey:(SecKeyRef _Nonnull)publicKey plainText:(NSData * _Nonnull)plainText SWIFT_WARN_UNUSED_RESULT;
/// 私钥解密数据(pkcs1)
+ (NSData * _Nullable)decryptWithPrivateKey:(SecKeyRef _Nonnull)privateKey cipherText:(NSData * _Nonnull)cipherText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 配对秘钥
SWIFT_CLASS("_TtC10TransitSDK10SecKeyPair")
@interface SecKeyPair : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10TransitSDK15SecurityManager")
@interface SecurityManager : NSObject
/// sha256加密
+ (NSString * _Nonnull)sha256WithPlainText:(NSString * _Nonnull)plainText SWIFT_WARN_UNUSED_RESULT;
/// sha256加密
+ (NSString * _Nonnull)sha256WithData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// 生成CMAC数据(AES-CMAC)
+ (NSArray<NSNumber *> * _Nullable)generateCmacWithKey:(NSArray<NSNumber *> * _Nonnull)key msg:(NSArray<NSNumber *> * _Nonnull)msg SWIFT_WARN_UNUSED_RESULT;
/// 验证CMAC
+ (BOOL)verifyCmacWithKey:(NSString * _Nonnull)key msg:(NSString * _Nonnull)msg remoteCmac:(NSArray<NSNumber *> * _Nonnull)remoteCmac SWIFT_WARN_UNUSED_RESULT;
/// AES/CBC 加密操作
+ (NSData * _Nullable)aesCBCEncryptWithKey:(NSData * _Nonnull)key data:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// AES/CBC 解密操作
+ (NSData * _Nullable)aesCBCDecryptWithKey:(NSData * _Nonnull)key data:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// AES/ECB 加密操作
+ (NSData * _Nullable)aesECBEncryptWithKey:(NSData * _Nonnull)key data:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// AES/ECB 解密操作
+ (NSData * _Nullable)aesECBDecryptWithKey:(NSData * _Nonnull)key data:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)crc16CcittWithHexString:(NSString * _Nonnull)hexString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// 字符串转换工具
SWIFT_CLASS("_TtC10TransitSDK11StringUtils")
@interface StringUtils : NSObject
/// 生成字典对象(从字典json字符串里面生成)
+ (NSDictionary<NSString *, id> * _Nonnull)toDictionaryWithString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
/// 生成String
+ (NSString * _Nonnull)toStringWithData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// 生成hexString
+ (NSString * _Nonnull)toHexStringWithString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
/// 生成hexString
+ (NSString * _Nonnull)toHexStringWithByte:(uint8_t)byte SWIFT_WARN_UNUSED_RESULT;
/// 生成hexString
+ (NSString * _Nonnull)toHexStringWithBytes:(NSArray<NSNumber *> * _Nonnull)bytes SWIFT_WARN_UNUSED_RESULT;
/// 生成hexString
+ (NSString * _Nonnull)toHexStringWithData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// 生成hexString(从十六进制字符串里去掉0x标记和空格)
+ (NSString * _Nonnull)toFormatHexStringWithHexString:(NSString * _Nonnull)hexString SWIFT_WARN_UNUSED_RESULT;
/// 生成hexString(从十六进制字符串里去掉0x标记和空格)
+ (NSString * _Nonnull)toFormatHexStringWithData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
/// 生成hexString(从十六进制字符串里去掉0x标记和空格)
+ (NSString * _Nonnull)toFormatHexStringWithBytes:(NSArray<NSNumber *> * _Nonnull)bytes SWIFT_WARN_UNUSED_RESULT;
/// 从十六进制字符串里去掉0x标记和空格
+ (NSString * _Nonnull)removeHexadecimalMarkAndSpaceWithHexString:(NSString * _Nonnull)hexString SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)hexadecimalToDecimalWithHexString:(NSString * _Nonnull)hexString SWIFT_WARN_UNUSED_RESULT;
/// 十进制 -> 二进制(8位)
+ (NSString * _Nonnull)decimalToBinaryWithDecimalString:(NSString * _Nonnull)decimalString SWIFT_WARN_UNUSED_RESULT;
/// 十六进制 -> 二进制
+ (NSString * _Nonnull)hexadecimalToBinaryWithHexString:(NSString * _Nonnull)hexString SWIFT_WARN_UNUSED_RESULT;
/// 十进制 -> 十六进制
+ (NSString * _Nonnull)decimalToHexadecimalWithDecimalString:(NSString * _Nonnull)decimalString SWIFT_WARN_UNUSED_RESULT;
/// 二进制 -> 十进制
+ (NSString * _Nonnull)binaryToDecimalWithBinaryString:(NSString * _Nonnull)binaryString SWIFT_WARN_UNUSED_RESULT;
/// 二进制 -> 十六进制
+ (NSString * _Nonnull)binaryToHexadecimalWithBinaryString:(NSString * _Nonnull)binaryString SWIFT_WARN_UNUSED_RESULT;
/// 补80(aes加密补80操作)
+ (NSString * _Nonnull)setAesEncryptPaddingWithMessage:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
/// 生成base64编码的字符串
+ (NSString * _Nonnull)toBase64EncodedStringWithBytes:(NSArray<NSNumber *> * _Nonnull)bytes SWIFT_WARN_UNUSED_RESULT;
/// 生成一个指定长度的随机数(1-32位长度)
+ (NSString * _Nonnull)generateRandomStringWithLength:(NSInteger)length SWIFT_WARN_UNUSED_RESULT;
/// 截取字符串
+ (NSString * _Nonnull)substringWithString:(NSString * _Nonnull)string fromIndex:(NSInteger)fromIndex SWIFT_WARN_UNUSED_RESULT;
/// 截取字符串
+ (NSString * _Nonnull)substringWithString:(NSString * _Nonnull)string toIndex:(NSInteger)toIndex SWIFT_WARN_UNUSED_RESULT;
/// 截取字符串
+ (NSString * _Nonnull)substringWithString:(NSString * _Nonnull)string fromIndex:(NSInteger)fromIndex toIndex:(NSInteger)toIndex SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK11TransitBean")
@interface TransitBean : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK23TranitOrderListResponse")
@interface TranitOrderListResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK7Transit")
@interface Transit : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK23TransitACardRegisterFee")
@interface TransitACardRegisterFee : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitAccountCard")
@interface TransitAccountCard : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK15TransitAppToken")
@interface TransitAppToken : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10TransitSDK18TransitCancelOrder")
@interface TransitCancelOrder : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK11TransitCard")
@interface TransitCard : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK17TransitCardDetail")
@interface TransitCardDetail : TransitCard
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK19TransitCardIssueFee")
@interface TransitCardIssueFee : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10TransitSDK23TransitCardIssueFeeResp")
@interface TransitCardIssueFeeResp : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK15TransitCardList")
@interface TransitCardList : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitCardPDesign")
@interface TransitCardPDesign : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK19TransitCardProgress")
@interface TransitCardProgress : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK19TransitCardRenewFee")
@interface TransitCardRenewFee : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10TransitSDK22TransitCardRenewFeeReq")
@interface TransitCardRenewFeeReq : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK21TransitCertAapplyResp")
@interface TransitCertAapplyResp : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK11TransitDict")
@interface TransitDict : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK20TransitClassTypeDict")
@interface TransitClassTypeDict : TransitDict
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK25TransitConcessionTypeDict")
@interface TransitConcessionTypeDict : TransitDict
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK20TransitConfiguration")
@interface TransitConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK13TransitDesign")
@interface TransitDesign : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10TransitSDK15TransitDictResp")
@interface TransitDictResp : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10TransitSDK18TransitDigitalCard")
@interface TransitDigitalCard : TransitCard
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitEligibility")
@interface TransitEligibility : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK16TransitException")
@interface TransitException : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10TransitSDK23TransitExchangeCertResp")
@interface TransitExchangeCertResp : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK22TransitExchangeKeyResp")
@interface TransitExchangeKeyResp : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK22TransitGenerateReOrder")
@interface TransitGenerateReOrder : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK32TransitGenerateReOrderRefundInfo")
@interface TransitGenerateReOrderRefundInfo : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK16TransitLengthMax")
@interface TransitLengthMax : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK30TransitLinkPaymentCardResponse")
@interface TransitLinkPaymentCardResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK35TransitLinkPaymentCardTokenResponse")
@interface TransitLinkPaymentCardTokenResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NFCTagReaderSession;

SWIFT_PROTOCOL("_TtP10TransitSDK24TransitNFCReaderDelegate_")
@protocol TransitNFCReaderDelegate
@optional
/// waitCardReading
/// \param session NFCTagReaderSession
///
- (void)waitCardReading:(NFCTagReaderSession * _Nonnull)session;
/// startCardReading
- (void)startCardReading:(NFCTagReaderSession * _Nonnull)session;
/// readCardSuccess
- (void)readCardSuccess:(NFCTagReaderSession * _Nullable)session;
/// readCardFailure
- (void)readCardFailure:(NFCTagReaderSession * _Nullable)session;
@end

typedef SWIFT_ENUM(NSInteger, TransitNFCType, open) {
  TransitNFCTypeCHECK_CARD_INFO = 0,
  TransitNFCTypeTRANSACTION = 1,
};


SWIFT_CLASS("_TtC10TransitSDK20TransitNetworkLogger")
@interface TransitNetworkLogger : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitOrderDetail")
@interface TransitOrderDetail : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitPaymentCard")
@interface TransitPaymentCard : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK30TransitPaymentCardListResponse")
@interface TransitPaymentCardListResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK19TransitPhysicalCard")
@interface TransitPhysicalCard : TransitCard
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK33TransitPhysicalTopupOrderResponse")
@interface TransitPhysicalTopupOrderResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK14TransitProduct")
@interface TransitProduct : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitProductFare")
@interface TransitProductFare : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK17TransitProductFee")
@interface TransitProductFee : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK25TransitProductFeeResponse")
@interface TransitProductFeeResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK15TransitProgress")
@interface TransitProgress : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK17TransitRefundCard")
@interface TransitRefundCard : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitRefundCards")
@interface TransitRefundCards : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK20TransitRefundListReq")
@interface TransitRefundListReq : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK19TransitRefundRecord")
@interface TransitRefundRecord : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK26TransitRenewResubmitDetail")
@interface TransitRenewResubmitDetail : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitRenewReview")
@interface TransitRenewReview : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK31TransitResettingPinInfoResponse")
@interface TransitResettingPinInfoResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK21TransitResubmitDetail")
@interface TransitResubmitDetail : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK13TransitReview")
@interface TransitReview : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK28TransitSdkOutTradeNoResponse")
@interface TransitSdkOutTradeNoResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK24TransitSdkSecretResponse")
@interface TransitSdkSecretResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK22TransitSendOtpResponse")
@interface TransitSendOtpResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK23TransitTopupEligibility")
@interface TransitTopupEligibility : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK15TransitTopupFee")
@interface TransitTopupFee : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK18TransitTransaction")
@interface TransitTransaction : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK35TransitUnlinkPaymentCardOTPResponse")
@interface TransitUnlinkPaymentCardOTPResponse : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10TransitSDK15TransitUserInfo")
@interface TransitUserInfo : TransitBean
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
