name: Danger

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  danger:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift@sha256:2e44d105d03a4282d8e7ea9a770d7393585ea2337a09bc4f1e3b49003ad4e7b1 # 3.13.0
        with:
            args: --failOnErrors --no-publish-check --remove-previous-comments
        env:
          GITHUB_TOKEN: ${{ github.token }}
